export class Er_orders {
  constructor(public er_order_id: any,
              public er_order_type_id_fk_orders: any,
              public er_order_shipping_id_fk_orders: any,
              public er_order_shipping_type_id_fk_orders: any,
              public se_seller_id_fk_orders: any,
              public co_city_id_fk_orders: any,
              public ac_school_id_fk_orders: any,
              public er_order_consecutive: any,
              public er_order_contract: any,
              public er_order_code: any,
              public er_order_guide: any,
              public er_order_previous_order: any,
              public er_order_date_application: any,
              public er_order_date_ship: any,
              public er_order_date_return: any,
              public er_order_observations: any,
              public er_order_ship_name: any,
              public er_order_ship_to: any,
              public er_order_ship_address: any,
              public er_order_ship_phone: any,
              public er_order_total: any,
              public er_order_invoiced: any,
              public er_order_material: any,
              public er_order_item: any,
              public er_order_file_list: any,
              public er_order_state: any,
              public er_order_active: any,
              public er_order_created_at: any) {
  }
}
